project:
  type: book
  output-dir: ../docs

book:
  title: "Public Health Environmental Surveillance Open Data Model (PHES-ODM) Documentation"
  repo-url: "https://github.com/Big-Life-Lab/PHES-ODM-Doc"
  chapters:
    - index.qmd
    - explanation.qmd
    - how-to.qmd
    - tutourials.qmd
    - part: ref-quide.qmd
      chapters:
        - parts.qmd
        - sets.qmd
        - languages.qmd
        - translations.qmd
        - tables.qmd
        - partTypes.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, ./assets/phes-odm.scss]
    code-copy: true
    code-overflow: wrap
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
  epub:
    css: ./assets/phes-odm.css
