project:
  type: book
  output-dir: ../docs

book:
  title: "Public Health Environmental Surveillance Open Data Model (PHES-ODM) Documentation"
  output-file: "ODM-documentation-v2.0.1"
  version: "2.0.1"
  date: last-modified
  date-format: iso
  license: CC 4.0 BY-SA
  repo-url: "https://github.com/Big-Life-Lab/PHES-ODM-Doc"
  repo-actions: [issue, source]
  repo-subdir: qmd
  downloads: [pdf, epub]
  sidebar:
    search: true
    logo: ./assets/ODM-logo.png
  chapters:
    - index.qmd
    - background.qmd
    - explanation.qmd
    - how-to.qmd
    - sampleRelationships.qmd
    - wide-names.qmd
    #- tutourials.qmd
    - protocols.qmd
    - part: ref-guide.qmd
      chapters:
        - parts.qmd
        - sets.qmd
        - tables.qmd
format:
  html:
    toc: true
    theme:
      light: [cosmo, ./assets/phes-odm.scss]
    code-copy: true
    code-overflow: wrap
    lang: en-ca
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
  epub:
    css: ./assets/phes-odm.css
