project:
  type: website
  output-dir: ../docs

website:
  title: "PHES-ODM-Documentation"
  image: "quarto.png"
  favicon: "favicon.png"
  site-url: https://quarto.org
  repo-url: https://github.com/Big-Life-Lab/PHES-ODM-Doc
  navbar:
    background: primary
    left:
      - href: explanation-documentation.qmd
        text: Home

format:
  html:
    toc: true
    theme:
      light: [cosmo]
    code-copy: true
    code-overflow: wrap