# Background - Environmental Surveillance and the ODM {.unnumbered}

Awareness of threats to public health is important for the function of modern health care systems, and environmental surveillance is presenting itself as very cost effective way to monitor for these threats. While environmental surveillance methods, like wastewater surveillance, are not entirely new, they certainly experienced an unprecedented expansion of uptake over the course of the covid-19 pandemic. 

Early on in the pandemic, the urgency with which new information was required meant that wastewater monitoring programs in particular were started quickly. This was true globally, with data often being collected in desktop spreadsheets and with labs running all their own PCR assays and assessing quality and doing data cleaning themselves. This work was crucial to monitoring viral levels in communities at the time, and so the urgency and speed of expansion which led to a very diverse field was perhaps unavoidable. Namely, the rapidly expanding field meant that new methods and measures were being rapidly introduced, with no consistent approach to reporting findings or coherent data quality standards. The field is also, by its very nature, complex with many systematic, environmental and laboratory-based factors affecting the signal. Furthermore, viral sequencing and other genetic measurements generate enormous amounts of complicated data. Add this to the fact that the field has many stakeholders who generate and use data all over the world, with data management and governance practices that can vary enormously, and are left with a field with enormous struggles sharing and collecting interoperable data.

To address issues of interoperability and to enable stronger data sharing, our team built and developed version one of the Public Health Environmental Surveillance Open Data Model (PHES-ODM, or ODM). A data model, like the ODM, seeks to replicate the real-world processes through which data is collected using data elements and data relationships. Ultimately, the goal of the ODM is to create a single, unified structure for data storage and collection, and in doing so allow for data to be shared, aggregated, and analyzed with greater ease, advancing the science of wastewater-based epidemiology (WBE) and of environmental surveillance as a whole. 

In version 1.0 and 1.1 of the ODM, a strong data model was developed and taken up by collaborators in the Ontario Wastewater Surveillance Initiative, among other programs. WBE has been advancing quickly through the pandemic, however, and version 1.0 was created before the community was aware that variants and sequencing would be of such crucial importance. Since version 1.0, wastewater testing has expanded from solely looking for severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2), to also test for other targets, including influenza, respiratory syncytial virus (RSV), poliovirus, and even antimicrobial drug resistance (AMR) and various enteropathogens. As such, version 2.0 of the ODM required a large-scale reworking of the original model. This has expanded the model to incorporate data from any kind of environmental surveillance (ie. surface testing, air measures, wastewater testing), to allow for the tracking of more granular metadata, and to record details on sequencing and variants. The work was done with the support and consultation of many experts and collaborators, most notably from the Public Health Agency of Canada's National Microbiology Lab; the European Commission Joint Research Centre; the Ontario Ministry of Environment, Conservation, and Parks; and many partners in academic labs across Canada. 

Version 2.0 of the ODM includes an entity relationship diagram (ERD) of the model, as well as a "master parts list" which details all of the components an values in the model. You will find these - along with how-to guides, tutorials, and reference materials - in this set of documentation for the model. 

## Objectives and Values of the ODM

The over-arching objectives for the ODM are to:

- Include provision for any biological, chemical or physical property, including antimicrobial resistance, drugs and toxins. Biological properties include variants, sequences, alleles, mutations and proteins.
- Include the ability to store data from samples from air, surface samples, and wastewater (water).
- Include protocol reporting, including metadata for methods that may affect measurement across laboratories.
- Include reporting of quality control and assurance. Each measure can have multiple quality control and assurance measures.

We seek to accomplish all of the above stated goals while staying true to the guiding values of the ODM project. These values are to:

- *Support Data Custodians and Data Users:* The data model should support data custodians and data users across the lifecycle of environmental surveillance. Users include wastewater laboratories, municipalities, public health (international, federal, provincial, and local), researchers, and others (citizen data scientists, data aggregators, news agencies). The lifecycle includes data collection and management in municipalities and laboratories, surveillance, research and other uses (public reporting by aggregator sites). For the ODM this means supporting users and building tools to support the ODM, and also means that we must make the ODM Comprehensive. The ODM must include measures from other wastewater dictionaries.
- *Support FAIR data:* In 2016, a diverse set of stakeholders— representing academia, industry, funding agencies, and scholarly publishers—designed, jointly endorsed, and published the ‘FAIR Guiding Principles for scientific data management and stewardship’.1 The intent of FAIR is to improve infrastructure supporting reuse of scholarly data based on four foundational principles: Findability, Accessibility, Interoperability, and Reusability. For the ODM this means making sure that the ODM makes for data that is findable, accessible, interoperable, and reusable by considering these attributes part of the core infrastructure.
- *Use an open science, open software approach:* Open-source software is software with source code that anyone can inspect, modify and enhance. Open-source initiatives embrace principles of open exchange, collaborative participation, rapid prototyping, transparency and community-oriented development. For the ODM this means that all work on the ODM is hosted in open-access environments, like GitHub, where anyone and everyone can transparently see the work being done, the rationale behind it, and can contribute to the project according to their ability.

## Orgnaization of the Documentation

The documentation for version 2.0 of the ODM was written and organized with [David Laing and Divio's Grand Unified Theory of Documentation](https://documentation.divio.com/#:~:text=The%20Grand%20Unified%20Theory%20of,guides%2C%20technical%20reference%20and%20explanation.) in mind. This means including four different pieces:

*Tutorials:* Oriented to learning, this piece must allow the newcomer to get started. This piece of the documentation should ideally take the form of a lesson. As an analogy, consider tutorials as being akin to teaching a small child how to cook.

*How-to guides:* Oriented to a goal,this piece must show how to solve a specific problem. This piece of the documentation should ideally take the form of a series of steps. As an analogy, consider how-to guides as being akin to a recipe in a cookery book.

*Reference:* Oriented to information, this piece must describe the machinery. This piece of the documentation should ideally take the form of a dry description. As an analogy, consider reference as being akin to a reference encyclopaedia article.

*Explanation:* Oriented to understanding, this piece must explain. This piece of the documentation should ideally take the form of a discursive explanation. As an analogy, consider explanation as being akin to an article on culinary social history.

We hope that the documentation serves its purpose and that you find it useful in figuring out how to best use the ODM and its suite of tools. If you do encounter any issues or questions that do not seem to have an easy answer, please [create an issue on our GitHub repository](https://github.com/Big-Life-Lab/PHES-ODM) or consult [our Discourse page](https://odm.discourse.group/).





