
name: build-docs-composite-action
runs:
  using: composite
  steps:
    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install tinytex
      run: quarto install tool tinytex
      shell: bash
    - name: setup-r
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.0.3"
    - name: Install R dependencies
      uses: r-lib/actions/setup-renv@v2
    - name: Render quarto
      run: quarto render ./qmd
      shell: bash
