
name: build-docs-composite-action
runs:
  using: composite
  steps:
    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install tinytex
      run: quarto install tool tinytex
      shell: bash
    - name: Install rmarkdown package
      run: R -e 'install.packages("rmarkdown")'
      shell: bash
    - name: Render quarto
      run: quarto render ./qmd
      shell: bash
