
name: build-docs-composite-action
runs:
  using: composite
  steps:
    - name: Install quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install tinytex
      run: quarto install tool tinytex
    - name: Render quarto
      run: quarto render ./qmd
