
# Parties <br /> Les parties sont l’élément élimentaire et fondamental de la description de tout ce qui se trouve dans l'ODM. Pensez à l'exemple des différentes pièces d'une voiture. Si vous possédez une voiture, votre garagiste peut accéder à une liste de pièces qui contient toutes les pièces de votre voiture -- jusqu'à chaque écrou et boulon. Cela est également vrai pour l'ODM. <br /> L'ODM possède un ID de partie (partID) et une description de partie (partDescription) pour chaque mesure, méthode et attribut. Il existe également des partID pour les catégories de mesures, les unités, les agrégations et d'autres parties. Vous trouverez ci-dessous la liste des parties.

```{rvml}```
var versionText = Première version publiée :
var updateText = Dernière mise à jour de la version :

var tableRow = {<a name="{{partID}}"></a>**{{partLabel}}**({{partID}}): {{partDesc}} {{partInstr}} </br>*Part Type:* <a href="#{{partType}}">{{partType}}</a></br>*Domain ID:* <a href="#{{domainID}}">{{domainID}}</a></br>*Speciment ID:* <a href="#{{specimenSet}}">{{specimenSet}}</a></br>*Compartment Set:* <a href="#{{compartSet}}">{{compartSet}}</a></br>*Group ID:* <a href="#{{groupID}}">{{groupID}}</a></br>*Class ID:* <a href="#{{classID}}">{{classID}}</a></br>*Nomenclature ID:* <a href="#{{nomenclatureID}}">{{nomenclatureID}}</a> </br>*Ontology Reference:* <a href="#{{ontologyRef}}">{{ontologyRef}}</a></br>*Latex Expression:* {{latExp}}</br>*Category Set ID:* <a href="#{{catSetID}}">{{catSetID}}</a></br>*Unit Set ID:* <a href="#{{unitSetID}}">{{unitSetID}}</a></br>*Aggregation Scale ID:* <a href="#{{aggScaleID}}">{{aggScaleID}}</a></br>*Quality Set ID:* <a href="#{{qualitySetID}}">{{qualitySetID}}</a></br>*Reference Link:* {{refLink}}</br>*Data Type:* <a href="#{{dataType}}">{{dataType}}</a></br>*Minimum Value:* {{minValue}}</br>*Maximum Value:* {{maxValue}}</br>*Minimum Length:* {{minLength}}</br>*Maximum Length:* {{maxLength}}}



{{filter:*, order:partID = ASC ,format(tableRow)}}

```{rvml}```


