
[partLabel]([partID]): [partDesc] [partInstr; if == NA, print = FALSE]
"Part Type:" [partType]
"Domain ID:" [domainID]
"Specimen ID:" [specimenID]
"Compartment Set:" [compartSet]
"Group ID:" [groupID]
"Class ID:" [classID]
"Nomenclature ID:" [nomenclatureID]
"Ontology Reference:" [ontologyRef]
"Latex Expression:" [latExp]	
"Category Set ID:" [catSetID]	
"Unit Set ID:" [unitSetID]
"Aggregation Scale ID:" [aggScaleID]	
"Aggregation Set ID:" [aggSetID]	
"Quality Set ID:" [qualitySetID]
"Reference Link:" [refLink]	
"Data Type:" [dataType]	
"Minimum Value:" [minValue]	
"Maximum Value:" [maxValue]	
"Minimumm Length:" [minLength]	
"Maximum Length:" [maxLength]


