
<!--` parts1 -->
# Parts

Parts are the smallest way of describing anything in the ODM. Think of the example of parts of a car. If you own a car, your garage can access a parts list that contains every part of your car -- right down to every nut and bolt. The same is true for the ODM.

The ODM has a part ID (partID) and part description (partDescription) for every measure, method and attribute. There are also partIDs for measure categories, units, aggreations, and other parts. Below is the part list.

<!--` parts1/ -->

```{rvml}```
var versionText = <!--` versionText -->Version first released: <!--` versionText/ -->
var updateText = <!--` updateText -->Version last updated: <!--` updateText/ -->

var tableRow = {<a name="{{partID}}"></a>**{{partLabel}}**({{partID}}): {{partDesc}} {{partInstr}} </br>*Part Type:* <a href="#{{partType}}">{{partType}}</a></br>*Domain ID:* <a href="#{{domainID}}">{{domainID}}</a></br>*Speciment ID:* <a href="#{{specimenSet}}">{{specimenSet}}</a></br>*Compartment Set:* <a href="#{{compartSet}}">{{compartSet}}</a></br>*Group ID:* <a href="#{{groupID}}">{{groupID}}</a></br>*Class ID:* <a href="#{{classID}}">{{classID}}</a></br>*Nomenclature ID:* <a href="#{{nomenclatureID}}">{{nomenclatureID}}</a> </br>*Ontology Reference:* <a href="#{{ontologyRef}}">{{ontologyRef}}</a></br>*Category Set ID:* <a href="#{{catSetID}}">{{catSetID}}</a></br>*Unit Set ID:* <a href="#{{unitSetID}}">{{unitSetID}}</a></br>*Aggregation Scale ID:* <a href="#{{aggScaleID}}">{{aggScaleID}}</a></br>*Quality Set ID:* <a href="#{{qualitySetID}}">{{qualitySetID}}</a></br>*Reference Link:* {{refLink}}</br>*Data Type:* <a href="#{{dataType}}">{{dataType}}</a></br>*Minimum Value:* {{minValue}}</br>*Maximum Value:* {{maxValue}}</br>*Minimum Length:* {{minLength}}</br>*Maximum Length:* {{maxLength}}</br> {{cat_info}}}



{{filter:*, order:partID = ASC ,format(tableRow)}}

```{rvml}```


